jsonplaceholder_url: "https://JSONplaceholder.typicode.com"
reqres_url: "https://reqres.in/api"
httpbin_url: "https://httpbin.org"
gorest_url: "https://gorest.co.in/public/v2"
gorest_token: "fede43efff932d1072d20f7e40641bcff22862c4e02d349f5491786200176390"
